import { Ticket } from "lucide-react"
import type { TicketRecord } from "@/types"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { EmptyState } from "@/components/ui/states"
import { formatTime, titleCase } from "@/lib/utils"

export function TicketPanel({ tickets }: { tickets: TicketRecord[] }) {
  const latest = tickets[0]

  return (
    <Card className="h-fit">
      <CardHeader>
        <div className="flex items-center gap-2">
          <div className="rounded-xl bg-emerald-50 p-2 text-emerald-700">
            <Ticket className="h-4 w-4" />
          </div>
          <div>
            <CardTitle>Active Ticket</CardTitle>
            <CardDescription>Generated by the Ticket Agent</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {!latest ? (
          <EmptyState
            title="No tickets yet"
            description="When the Employee Reception flow creates a ticket, it will appear here."
            className="py-8"
          />
        ) : (
          <div className="space-y-3">
            <div className="rounded-xl border border-emerald-100 bg-emerald-50/60 p-3">
              <p className="text-xs uppercase tracking-wide text-emerald-700/70">Ticket ID</p>
              <p className="font-[Outfit] text-lg font-semibold text-emerald-900">
                {latest.ticketId}
              </p>
            </div>
            <MetaRow label="Decision" value={titleCase(latest.decision)} />
            <MetaRow label="Priority" value={latest.priority} />
            <MetaRow label="Assigned Team" value={titleCase(latest.assignedTeam)} />
            <MetaRow label="Status" value={titleCase(latest.status)} />
            <MetaRow label="Intent" value={titleCase(latest.intent)} />
            <MetaRow label="Sentiment" value={titleCase(latest.sentiment)} />
            <MetaRow label="Created" value={formatTime(latest.createdAt)} />
            <div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">
              {latest.message}
            </div>
            <div className="flex flex-wrap gap-1.5">
              <Badge variant="green">{titleCase(latest.intent)}</Badge>
              <Badge
                variant={
                  latest.priority.toUpperCase() === "URGENT" ? "amber" : "secondary"
                }
              >
                {latest.priority}
              </Badge>
              <Badge variant="outline">{titleCase(latest.status)}</Badge>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-3 text-sm">
      <span className="text-slate-500">{label}</span>
      <span className="font-medium text-slate-800">{value}</span>
    </div>
  )
}
