from dataclasses import dataclass


@dataclass
class IntentResult:
    intent: str
    confidence: float


class IntentService:

    def classify(self, message: str) -> IntentResult:

        message = message.lower()

        technical_keywords = [
            "vpn",
            "wifi",
            "network",
            "internet",
            "computer",
            "password",
            "login",
            "email",
            
            # Connectivity
            "router",
            "modem",
            "ethernet",
            "dns",
            "ip",
            "connection",
            "connectivity",

            # Authentication
            "signin",
            "account",
            "username",
            "authentication",
            "mfa",
            "otp",

            # Devices
            "printer",
            "scanner",
            "laptop",
            "desktop",
            "keyboard",
            "mouse",
            "monitor",
            "camera",
            "webcam",

            # Systems
            "server",
            "database",
            "sql",
            "mysql",
            "postgresql",
            "api",
            "docker",
            "windows",
            "linux",
            "ubuntu",
            "excel",
            "outlook",
            "teams",

            # Technical problems
            "error",
            "issue",
            "problem",
            "crash",
            "timeout",
            "disconnect",
            "failed",
            "failure",
            "offline",
            "bug",

            # Arabic
            "شبكة",
            "واي فاي",
            "وايفاي",
            "انترنت",
            "إنترنت",
            "راوتر",
            "مودم",
            "اتصال",
            "تسجيل دخول",
            "كلمة مرور",
            "باسورد",
            "طابعة",
            "كمبيوتر",
            "حاسوب",
            "قاعدة بيانات",
            "سيرفر",
            "خادم",
            "ويندوز",
            "لينكس",
            "إكسل",
            "أوتلوك",
            "تيمز",
            "مشكلة",
            "عطل",
            "خطأ",
            "تعطل",
            "فشل",
            "لا يعمل",
            "الدخول",
            "تسجيل الدخول",
            "تعذر الدخول",
            "لا يمكنني الدخول",
            "لا استطيع الدخول",
            "لا أستطيع الدخول",
            "نسيت كلمة المرور",
            "مشكلة",
            "عطل",
            "خطأ",
            "تعطل",
            "فشل",
            "لا يعمل",
            "لا تعمل",
            "لا يفتح",
            "لا تفتح",
            "علق",
            "تجمد",
            "بطء",
            "بطيء",
            "انقطع",
            "انقطاع",
            "غير متصل",
            "الدخول",
            "تسجيل الدخول",
            "تسجيل دخول",
            "تسجيل",
            "تعذر الدخول",
            "لا يمكنني الدخول",
            "لا استطيع الدخول",
            "لا أستطيع الدخول",
            "نسيت كلمة المرور",
            "إعادة تعيين كلمة المرور",
            "الحساب",
            "حسابي",
            "شبكة",
            "واي فاي",
            "وايفاي",
            "إنترنت",
            "انترنت",
            "الاتصال",
            "اتصال",
            "راوتر",
            "مودم",
            "طابعة",
            "برنتر",
            "ماسح",
            "سكانر",
            "حاسوب",
            "كمبيوتر",
            "لابتوب",
            "حاسبة",
            "شاشة",
            "كيبورد",
            "لوحة مفاتيح",
            "ماوس",
            "فأرة",
            "كاميرا",
            "ويب كام",
            "ميكروفون",
            "ويندوز",
            "لينكس",
            "أوتلوك",
            "اوتلوك",
            "إكسل",
            "اكسل",
            "تيمز",
            "قاعدة بيانات",
            "سيرفر",
            "خادم",
            "خادم قاعدة البيانات",
            "اختراق",
            "تهكير",
            "اختراق الحساب",
            "دخول غير مصرح",
            "صلاحيات",
            "إذن",
            "صلاحية",
            "فيروس",
            "برمجية خبيثة",
            "لا تعمل"
        ]

        hr_keywords = [
            "leave",
            "vacation",
            "salary",
            "promotion",
            "policy",
            "holiday",
            "attendance",

            "employee",
            "employees",
            "payroll",
            "benefits",
            "training",
            "recruitment",
            "hiring",
            "interview",
            "resignation",
            "insurance",
            "bonus",

            "إجازة",
            "اجازة",
            "راتب",
            "رواتب",
            "موظف",
            "موظفين",
            "توظيف",
            "تدريب",
            "ترقية",
            "دوام",
            "حضور",
            "استقالة",
            "تأمين",
            "مكافأة",
            "إجازة",
            "راتب",
            "رواتب",
            "موظف",
            "موظفين",
            "دوام",
            "حضور",
            "انصراف",
            "بصمة",
            "ترقية",
            "تقييم",
            "توظيف",
            "مقابلة",
            "استقالة",
            "استقالتي",
            "تأمين",
            "تدريب",
            "مكافأة",
            "بدل",
            "حوافز",
            "إجازات",
            "إجازة مرضية",
            "إجازة سنوية",
            "موارد بشرية",
            "الموارد البشرية",
            "سياسة" 
        ]

        for word in technical_keywords:
            if word in message:
                return IntentResult(
                    intent="technical",
                    confidence=0.95,
                )

        for word in hr_keywords:
            if word in message:
                return IntentResult(
                    intent="hr",
                    confidence=0.95,
                )

        return IntentResult(
            intent="unknown",
            confidence=0.50,
        )